import fs from 'node:fs';import sharp from 'sharp';
const ps=JSON.parse(fs.readFileSync('src/products.json'));
const flexi=ps.find(p=>p.id==='trubuild-aqualock-flexi');if(!flexi.applications.includes('Wet Areas'))flexi.applications.push('Wet Areas');
for(const p of ps){p.sourceNotes=[];if(/sbr-|trufix-|stylo-|rooftect-prime/.test(p.id))p.sourceNotes.push('Some official copy and documents use legacy product names; confirm the current code and document revision.');if(!p.packaging)p.sourceNotes.push('Current packaging not listed in the source page’s sizes section.');}
const white=ps.find(p=>p.id==='trufix-220-plus-white');white.sourceNotes.push('Source description calls the white variant grey; colour must be confirmed from current documentation.');
const roof=ps.find(p=>p.id==='trubuild-rooftect-advanced');roof.sourceNotes.push('FAQ formulation and coating-thickness claims conflict with the structured technical content; FAQ claims are excluded.');
fs.writeFileSync('src/products.json',JSON.stringify(ps,null,2));
await sharp('public/images/wordmark-clean.png').resize(600).webp({quality:95}).toFile('public/images/wordmark-clean.webp');
const docs=JSON.parse(fs.readFileSync('src/resources.json'));
const esc=s=>String(s).replaceAll('|','\\|').replaceAll('\n',' ');
fs.writeFileSync('docs/CONTENT-INVENTORY.md',`# TruBuild content and product inventory\n\nReviewed 5 October 2026. 32 navigation URLs inspected; 31 distinct valid product pages and 46 official PDFs retained. CPS 111’s URL returns CFP 525 content. CPS 111 is available as a document-only record; no fabricated product page was created.\n\n## Product inventory\n\n| Product | Category | Applications | Packaging | Source | Verification notes |\n|---|---|---|---|---|---|\n`+ps.map(p=>`| ${esc(p.name)} | ${esc(p.category)} | ${esc(p.applications.join('; '))} | ${esc(p.packaging||'Not listed — confirm')} | [Official page](${p.source}) | ${esc(p.sourceNotes.join(' ')||'Structured page content captured')} |`).join('\n')+'\n\n## Documents\n\n| Document | Official source | Local copy |\n|---|---|---|\n'+docs.map(d=>`| ${esc(d.title)} | [PDF](${d.url}) | ${d.local||'External'} |`).join('\n')+'\n\n## Asset inventory\n\nEach product record stores imageSource and the optimized local image. Product packaging is authentic official website imagery. Architecture and interior are generated illustrations, marked as such in the interface. User-supplied yellow/white logo reference is preserved under research. No facility, people, project or certification photography was fabricated.\n\n## Company content\n\nBrand: Astral TruBuild, an Astral Limited brand. Scope: waterproofing, tiling, grouting, exterior coatings and construction repair. Source: https://www.trubuild.in/about-us/ . Contact: toll-free 1800 309 9393; customercare@astraladhesives.com; Astral House, 207/1, Behind Rajpath Club, Off S.G. Highway, Ahmedabad 380059. Source: https://www.trubuild.in/contact-us/ . Statistics, manufacturing sites and certification badges are not carried forward without current scope verification.\n');
