import React from "react";
import { createRoot, hydrateRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import "./fonts.css";
import "./styles.css";
import "./solutions.css";
import "./product-hero.css";
import "./typography.css";
const root = document.getElementById("root");
const app = <BrowserRouter><App /></BrowserRouter>;
const currentPath = window.location.pathname.replace(/\/+$/, "") || "/";
if (root.dataset.prerendered && root.dataset.route === currentPath && !window.location.search) hydrateRoot(root, app);
else createRoot(root).render(app);
