// Editorial search-intent map. Product claims are grounded in the linked TDS.
// Keywords guide writing; they are not emitted as a meta-keywords tag.
export const solutionContent = {
  roof: {
    title: 'Roof & Terrace Waterproofing Solutions | TruBuild',
    description: 'Explore TruBuild roof and terrace waterproofing. Compare exposed and protected roof systems, surface preparation, coverage and product technical data sheets.',
    heading: 'Roof', accent: 'Waterproofing.',
    keywords: ['roof waterproofing', 'terrace waterproofing', 'roof leakage solution', 'waterproofing coating for terrace', 'terrace waterproofing cost'],
    question: 'How do you choose a roof waterproofing system?',
    answer: 'Choose roof waterproofing by the existing surface, sunlight exposure, foot traffic and drainage. An exposed terrace needs a weather-resistant system suited to that substrate; a membrane beneath tiles or screed needs compatible protection. Repair defects and detail outlets, pipe entries and parapet junctions before applying the specified coating.',
    intro: 'A new concrete terrace and a leaking tiled roof need different preparation. Start by identifying where water enters, whether the existing finish is sound and how the roof will be used after treatment. TruBuild roof products include acrylic coatings, cementitious coatings, polyurethane membranes, primers and repair materials, each with its own role.',
    selectionTitle: 'Exposed roof or protected terrace?',
    choices: [
      ['An exposed concrete terrace', 'Assess weather exposure, surface condition and drainage before shortlisting a roof coating. Review Rooftect product guidance for its specified substrate, primer and coating build-up. A reflective finish does not remove the need to resolve standing water.', 'trubuild-rooftect-advanced'],
      ['Waterproofing below screed or tiles', 'Review a cementitious coating such as Aqualock Flexi for the intended build-up. Its TDS requires protection for trafficable finishes; the waterproofing layer should not be treated as a wearing surface.', 'trubuild-aqualock-flexi'],
      ['A protected polyurethane membrane', 'TRU PU is a bitumen-modified membrane for protected applications. Its TDS excludes permanent immersion. Do not assume that all polyurethane products have the same exposure limits or curing schedule.', 'trubuild-waterproofing-membrane-tru-pu'],
    ],
    steps: [
      ['Survey the roof', 'Check falls, drainage outlets, existing coatings, cracks, pipe penetrations and the roof-to-parapet junction. Identify loose finishes and the source of leakage before deciding what can stay.'],
      ['Prepare and detail', 'Repair the substrate and prepare junctions using the selected system. Follow its primer and surface-moisture requirements; cementitious and polyurethane systems do not share one universal preparation method.'],
      ['Apply, cure and protect', 'Follow the selected TDS for mixing, coverage, coat intervals and curing. Complete the specified water test before covering the membrane, and provide screed or other protection where required.'],
    ],
    faqs: [
      ['Which waterproofing is best for a terrace?', 'There is no single best terrace waterproofing product for every roof. The right shortlist depends on whether the roof is exposed or protected, the substrate, drainage and expected traffic. Compare the product TDS against these conditions rather than choosing by chemistry or price alone.'],
      ['Can I waterproof over existing terrace tiles?', 'Only use an over-tile system that explicitly supports the existing tile surface and its preparation. Check for hollow or loose tiles, failed grout and trapped moisture first. A roof coating should not be assumed to bond to glazed tiles without the specified preparation and primer.'],
      ['How much Aqualock Flexi is needed for a terrace?', 'The final Aqualock Flexi TDS states 1.8–2 kg/m² for two coats at 1.2–1.5 mm dry film thickness. For 100 m², this is 180–200 kg before allowances for surface profile, detailing and wastage. Pack sizes are 12 kg and 48 kg.'],
      ['How long before a roof waterproofing ponding test?', 'Use the curing period in the selected product TDS. Aqualock and Aqualock Flexi require at least seven days before ponding tests; TRU PU specifies ten days. These are product-specific requirements, not a common waiting period for all roof coatings.'],
      ['What determines terrace waterproofing cost?', 'Cost depends on roof area, removal of existing finishes, repairs, detailing, primer, coating consumption, protection and labour. Ask for a quotation that identifies the complete system and specified thickness. A price per square foot without the preparation and build-up is difficult to compare.'],
    ],
    related: ['exterior', 'sealants', 'repair'],
    documents: ['trubuild-aqualock-flexi', 'trubuild-aqualock', 'trubuild-waterproofing-membrane-tru-pu'],
  },
  tiling: {
    title: 'Tile Adhesives & Grouting Solutions | TruBuild',
    description: 'Choose tile adhesives and grouts for your tile type, size, substrate and exposure. Explore TruBuild TRUFIX and STYLO products, guidance and technical data.',
    heading: 'Tiling', accent: '& Grouting.',
    keywords: ['tile adhesive', 'tile grout', 'epoxy grout', 'tile adhesive for vitrified tiles', 'tile adhesive vs cement'],
    question: 'How do you choose tile adhesive and grout?',
    answer: 'Choose tile adhesive by tile material and size, the substrate, wall or floor location, and dry, wet or exterior exposure. Choose grout separately for joint width, finish and service conditions. The waterproofing layer, adhesive, grout and movement joints each perform a different job in a complete tile installation.',
    intro: 'A small ceramic floor tile in a dry room is a different installation from large-format tiles on a wet-area wall. Match the fixing system to the job before comparing products. The TRUFIX range covers different adhesive applications, while STYLO provides cementitious and epoxy grouting options.',
    selectionTitle: 'Match the fixing system to the installation.',
    choices: [
      ['Interior floor tiles', 'TRUFIX 110 is listed for interior floor fixing. Check the supported tile type, size and substrate in its document before using it on a wall or in another exposure.', 'trufix-110'],
      ['Cementitious tile joints', 'STYLO CEM is a tile grout. Check the permitted joint width, preparation and curing conditions separately from the adhesive specification.', 'trubuild-stylo-cem'],
      ['Epoxy tile grouting', 'Review STYLO 3K for an epoxy grout option. Check its application and cleaning instructions, working time and suitability for the intended exposure.', 'trubuild-stylo-3k'],
    ],
    steps: [
      ['Record the installation', 'Identify tile material, dimensions and backing, substrate type and condition, location and exposure. Include any existing tiles or waterproofing beneath the new finish.'],
      ['Prepare the substrate', 'Start with a sound, clean and appropriately level surface. Complete the specified wet-area waterproofing and curing before installing a compatible tile system.'],
      ['Fix and finish', 'Follow the adhesive TDS for water addition, open time, application thickness and coverage. Observe the waiting period before grouting, and detail movement joints separately from ordinary tile joints.'],
    ],
    faqs: [
      ['Is tile adhesive the same as tile grout?', 'No. Tile adhesive bonds tiles to the substrate, while tile grout fills the joints between tiles. Select both for the installation; a suitable grout does not compensate for the wrong adhesive or poor surface preparation.'],
      ['Can I use one adhesive for every tile size?', 'Do not assume so. Tile dimensions, material, weight, substrate and location affect the selection. Check the permitted tile size and application in the specific TRUFIX document, especially for large-format tiles and wall installations.'],
      ['Does epoxy grout replace bathroom waterproofing?', 'No. A tiled wet-area system still needs the specified waterproofing beneath the finish and correctly detailed corners, drains and penetrations. Grout between tiles is one part of that system.'],
      ['Is tile adhesive better than a traditional cement bed?', 'The choice depends on the specified installation. Proprietary adhesives have product-specific mixing and application requirements; assess them against the tile, substrate and exposure. Do not substitute a product without checking the required fixing method.'],
    ],
    related: ['wet', 'tanks', 'sealants'], documents: ['trufix-110', 'trubuild-stylo-cem', 'trubuild-stylo-3k'],
  },
  wet: {
    title: 'Bathroom & Wet Area Waterproofing | TruBuild',
    description: 'Plan bathroom waterproofing beneath tiles. Explore TruBuild coatings, pipe-entry sealing, surface preparation, curing and wet-area product data sheets.',
    heading: 'Wet', accent: 'Areas.',
    keywords: ['bathroom waterproofing', 'bathroom leakage solution', 'waterproofing under tiles', 'wet area waterproofing', 'bathroom floor waterproofing'],
    question: 'What does bathroom waterproofing need to cover?',
    answer: 'Bathroom waterproofing should form a continuous system beneath the finish across the specified floor and wall areas, with details at wall-floor junctions, drains and pipe entries. First distinguish a plumbing leak from water entering through the building fabric. Complete the coating, curing and water test before tiling.',
    intro: 'Wet-area leaks often appear in the room below or on the other side of a wall. The visible damp patch alone does not identify the source. A planned system deals with the substrate and the details that interrupt it, then coordinates waterproofing with the tile adhesive, grout and joint seals.',
    selectionTitle: 'Plan the waterproofing beneath the finish.',
    choices: [
      ['Concrete and masonry surfaces', 'Aqualock is a two-component cementitious coating listed for bathrooms, kitchens and other applications. Follow its 1:2 liquid-to-powder ratio by weight and do not add water.', 'trubuild-aqualock'],
      ['A flexible cementitious coating', 'Aqualock Flexi is listed for wet areas. Its preparation, mixing and curing requirements apply before installing the next layer; it is not a finished traffic surface.', 'trubuild-aqualock-flexi'],
      ['Gaps around pipe entries', 'Boretite is an epoxy-based bore-packing system for gaps between pipes and concrete. Pipe-entry treatment is a detail within the wider wet-area waterproofing system.', 'trubuild-boretite'],
    ],
    steps: [
      ['Find the source', 'Check plumbing, drainage, floor falls and the condition of the existing tile installation. Repair leaking supply or waste pipes before treating the surrounding construction.'],
      ['Detail vulnerable junctions', 'Prepare sound concrete or masonry and treat drains, pipe entries and wall-floor junctions using the selected system. Avoid leaving gaps in continuity at changes of plane.'],
      ['Test before tiling', 'Apply and cure the coating to its TDS. Complete the specified water test before covering the work, then select an adhesive and grout suitable for wet-area use.'],
    ],
    faqs: [
      ['Can bathroom leakage be fixed by replacing grout?', 'Replacing failed grout may address a local tile-joint defect, but it will not repair a leaking pipe or a failed waterproofing layer beneath the tiles. Identify the source before deciding whether local repair or removal of the finish is needed.'],
      ['Which TruBuild products are used for bathroom waterproofing?', 'Aqualock and Aqualock Flexi list wet-area applications. Boretite addresses suitable pipe-to-concrete gaps. Each has a different role; shortlist products against the substrate and complete system requirements in the linked TDS.'],
      ['How much Aqualock is required?', 'The final TDS states 1.65–1.75 kg/m² for two coats at 0.8–1 mm dry film thickness. Measure all treated surfaces and allow separately for junctions, surface condition and wastage.'],
      ['When can I water-test Aqualock Flexi?', 'Its final TDS requires at least seven days before ponding tests or filling water-retaining structures. Follow the full curing and protection instructions before covering the membrane.'],
    ],
    related: ['tiling', 'sealants', 'repair'], documents: ['trubuild-aqualock', 'trubuild-aqualock-flexi', 'trubuild-boretite'],
  },
  exterior: {
    title: 'Exterior Wall Waterproofing & Crack Repair | TruBuild',
    description: 'Explore exterior wall waterproofing, plaster crack fillers and water repellents from TruBuild. Choose by wall finish, crack condition and moisture source.',
    heading: 'Exterior', accent: 'Waterproofing.',
    keywords: ['exterior wall waterproofing', 'wall seepage solution', 'wall crack filler', 'external wall waterproof coating', 'water repellent for walls'],
    question: 'How do you treat water seepage through an exterior wall?',
    answer: 'Identify the entry point before coating an exterior wall. Check plaster cracks, wall joints, window surrounds, parapets and adjacent roof details. Repair defects, prepare the substrate and choose either the specified protective coating system or a compatible water repellent for a porous finish. Paint alone is not a diagnosis.',
    intro: 'Wall seepage after rain, cracked plaster and moisture at a window opening can require different treatments. First establish whether the water is coming through the wall, from the roof or from plumbing. Then decide whether the finish will be coated or its original appearance retained.',
    selectionTitle: 'Choose by wall condition and finish.',
    choices: [
      ['Non-structural plaster cracks', 'Crackfill Paste is listed for non-structural plastered masonry cracks up to 5 mm. Its TDS excludes structural cracks, expansion joints, separation gaps and cracks with running water.', 'trubuild-crack-filler-cfp-425'],
      ['A coated exterior wall', 'Explore the Walltect coating range and its specified preparation. Primer, basecoat and finish should be selected as a compatible build-up for the wall condition.', 'trubuild-walltect-top-coat'],
      ['A porous finish to retain', 'WRP 777 is a ready-to-use silane-based water repellent for porous construction surfaces, designed to retain appearance. Check substrate suitability and coverage; it is not a substitute for repairing open cracks.', 'trubuild-water-repellent-wrp-777'],
    ],
    steps: [
      ['Trace rain entry', 'Inspect roof-wall junctions, parapets, window details, cracks and penetrations. Distinguish rain penetration from plumbing leakage before choosing the treatment area.'],
      ['Repair and prepare', 'Remove loose material and treat suitable non-structural defects using the appropriate repair product. Moving joints and structural defects need their own treatment approach.'],
      ['Apply the selected finish', 'Follow the coating or repellent TDS for substrate condition, application and coverage. Check a small area where retaining the appearance of masonry or stone is important.'],
    ],
    faqs: [
      ['Can wall crack filler be used in expansion joints?', 'Crackfill Paste is not specified for expansion joints or structural cracks. A moving joint needs a sealant and joint design suited to the expected movement, rather than a general plaster crack filler.'],
      ['What is the difference between a water repellent and a wall coating?', 'A water repellent is selected for compatible porous surfaces where the original appearance is to be retained. A wall coating forms a specified protective finish. Substrate, defects and the desired appearance determine which approach to investigate.'],
      ['Can WRP 777 be diluted?', 'No. The final WRP 777 TDS describes a ready-to-use product and says not to dilute it. Follow its substrate preparation and application instructions.'],
      ['How much WRP 777 is needed for a wall?', 'The final TDS gives 5–6 m²/L/coat on porous substrates and 7–8 m²/L/coat on low-porosity substrates. Surface absorption affects consumption, so use the rate appropriate to the actual wall.'],
    ],
    related: ['roof', 'sealants', 'repair'], documents: ['trubuild-crack-filler-cfp-425', 'trubuild-water-repellent-wrp-777', 'trubuild-walltect-top-coat'],
  },
  repair: {
    title: 'Concrete Repair, Bonding Agents & Grouts | TruBuild',
    description: 'Explore TruBuild concrete repair materials, SBR latex, bonding agents and non-shrink grout. Match the product to the defect, substrate and repair method.',
    heading: 'Concrete', accent: 'and Mortar.',
    keywords: ['concrete repair materials', 'concrete bonding agent', 'SBR latex for concrete repair', 'non shrink grout', 'plaster bonding agent'],
    question: 'Which material should you use for concrete repair?',
    answer: 'Choose concrete repair materials by the defect and the job: modifying a repair mortar, bonding new material to old concrete, filling a baseplate gap or bonding plaster to RCC. These are different applications. Assess the cause and extent of damage before treating the visible surface, especially where concrete is loose or reinforcement is exposed.',
    intro: 'A bonding agent, a mortar modifier and a non-shrink grout are not interchangeable. The substrate, repair depth, loading and placement method determine the shortlist. TruBuild offers latex and acrylic modifiers, epoxy systems, plaster bonding products and cementitious grout for their documented uses.',
    selectionTitle: 'Start with the repair task.',
    choices: [
      ['Modify mortar or a bonding slurry', 'SBR 333 is a styrene-butadiene latex for waterproofing, repair mortar and bonding. Use the proportion for the chosen application rather than transferring a waterproofing ratio to a mortar mix.', 'trubuild-sbr-333'],
      ['Grout beneath a baseplate', 'Non-Shrink Grout HS lists a 10–100 mm gap range and different water additions for flowable, pourable and stiff consistency. Select the consistency for the placement method.', 'trubuild-non-shrink-grout-hs'],
      ['Bond plaster to concrete', 'Plasterbond is a polymeric bonding coating for gypsum or cement-sand plaster on RCC and concrete. Check surface preparation and the waiting period before plastering.', 'trubuild-plasterbond'],
    ],
    steps: [
      ['Assess the defect', 'Record depth, area, movement, loading and moisture conditions. Establish the cause of deterioration and a repair specification where the condition affects structural performance.'],
      ['Prepare a sound base', 'Remove unsound material and contaminants using the specified repair procedure. Follow the selected product requirements for surface moisture, priming and access for placement.'],
      ['Mix, place and cure', 'Measure components and water accurately. Respect working time and the required continuity of placement; cure and protect the repair for the stated period before loading or finishing.'],
    ],
    faqs: [
      ['Is SBR latex a ready-made repair mortar?', 'No. SBR 333 is a latex used in specified mixes for repair and bonding applications. Follow the TDS mix for the intended use, including the cement, sand, water and latex proportions where applicable.'],
      ['How much water does Non-Shrink Grout HS need?', 'For a 20 kg bag, the final TDS states 3.8 L for flowable consistency, 3.2 L for pourable consistency and 2.8 L for stiff consistency. The published strength values use a water-to-powder ratio of 0.16.'],
      ['Can plaster crack filler repair structural concrete damage?', 'Do not use a non-structural plaster crack filler as a structural repair system. Crackfill Paste explicitly excludes structural cracks. Establish the repair method and material requirements for the actual defect.'],
      ['What is the difference between Plasterbond and SBR 333?', 'Plasterbond is a prepared bonding coating for plaster on concrete or RCC. SBR 333 is a latex used in specified bonding, repair-mortar and waterproofing mixes. Choose by the documented task rather than substituting one for the other.'],
    ],
    related: ['exterior', 'basement', 'roof'], documents: ['trubuild-sbr-333', 'trubuild-non-shrink-grout-hs', 'trubuild-plasterbond'],
  },
  basement: {
    title: 'Basement & Foundation Waterproofing | TruBuild',
    description: 'Explore basement and foundation waterproofing with TruBuild. Understand positive and negative sides, sheet membranes, crystalline treatments and detailing.',
    heading: 'Substructure', accent: 'Waterproofing.',
    keywords: ['basement waterproofing', 'foundation waterproofing', 'negative side waterproofing', 'retaining wall waterproofing', 'basement waterproofing membrane'],
    question: 'What is positive-side versus negative-side waterproofing?',
    answer: 'Positive-side waterproofing is applied on the side facing the incoming water, such as the outside of a retaining wall. Negative-side waterproofing is applied on the opposite face, such as an accessible basement interior. Select a product expressly suited to that pressure direction, substrate and water exposure; the two positions are not interchangeable.',
    intro: 'Below-ground waterproofing requires attention to construction joints, service entries, continuity between the slab and walls, and protection during subsequent work. New construction may allow external access; an existing basement may only be accessible from inside. That difference changes the system options.',
    selectionTitle: 'Choose around access and water pressure.',
    choices: [
      ['An accessible below-ground face', 'Trushield is a self-adhesive waterproofing sheet membrane for below-ground structures. Plan laps, penetrations and protection as part of the system. Its TDS does not specify it as a UV-exposed finish.', 'trubuild-trushield'],
      ['Concrete or masonry coating', 'Aqualock Flexi lists positive- and negative-side applications. Check the pressure, surface condition and detailing requirements in its TDS against the basement specification.', 'trubuild-aqualock-flexi'],
      ['Crystalline treatment for concrete', 'Crystaseal 1K is a cementitious crystalline treatment. Review substrate preparation, application method and curing for the concrete structure; it does not replace the design of construction or movement joints.', 'trubuild-crystaseal-1k'],
    ],
    steps: [
      ['Establish access and exposure', 'Identify the face that can be treated, the substrate and the expected water conditions. Record cracks, joints, penetrations and interfaces with adjoining construction.'],
      ['Plan continuous detailing', 'Specify how the wall and slab treatments connect and how entries and joints are sealed. Coordinate drainage and protection with the waterproofing design.'],
      ['Inspect before covering', 'Follow the selected TDS for surface preparation, laps or coating coverage, curing and protection. Inspect continuity before backfilling or installing finishes that hide the work.'],
    ],
    faqs: [
      ['Can a basement be waterproofed from the inside?', 'An internal treatment may be considered where external access is unavailable, but the product must support negative-side conditions. Diagnose active leakage, joints and substrate defects before specifying an internal coating.'],
      ['Can Trushield be left exposed to sunlight?', 'The final Trushield TDS states that it is not UV or weather resistant. Treat it as a below-ground membrane within its specified application and protection requirements.'],
      ['Is waterproof concrete enough at construction joints?', 'The joints, penetrations and interfaces still need a waterproofing detail. A concrete treatment or admixture does not itself establish a continuous seal at every interruption in the structure.'],
      ['What overlap does Trushield require?', 'The final TDS specifies minimum side overlaps of 50 mm and end overlaps of 100 mm. Include these laps when estimating material, and follow the full installation and protection requirements.'],
    ],
    related: ['repair', 'sealants', 'tanks'], documents: ['trubuild-trushield', 'trubuild-aqualock-flexi', 'trubuild-crystaseal-1k'],
  },
  tanks: {
    title: 'Water Tank & Swimming Pool Waterproofing | TruBuild',
    description: 'Explore TruBuild waterproofing for concrete water tanks and pools. Review immersion suitability, curing, coating coverage and product technical documents.',
    heading: 'Water Tanks', accent: '& Other Areas.',
    keywords: ['water tank waterproofing', 'swimming pool waterproofing', 'concrete water tank leakage', 'waterproof coating for water tank', 'tank waterproofing curing time'],
    question: 'How do you choose waterproofing for a water tank or pool?',
    answer: 'Choose a system documented for the water-retaining structure, its substrate and intended water use. Check continuous immersion, relevant water-contact requirements, joints and pipe entries, curing before filling, and compatibility with any tile finish. A general roof waterproofing coating should not automatically be used inside a tank or swimming pool.',
    intro: 'A concrete storage tank, a tiled pool and a below-ground reservoir have different finishing and service requirements. Define the use of the water and the construction details before selecting a coating. Review product documentation for the complete system, not just its waterproofing label.',
    selectionTitle: 'Consider the complete water-retaining structure.',
    choices: [
      ['Cementitious tank coating', 'Aqualock lists water tanks, reservoirs and swimming pools. Follow the specified substrate preparation, two-coat coverage and curing before filling.', 'trubuild-aqualock'],
      ['Flexible cementitious waterproofing', 'Aqualock Flexi lists water-retaining applications and a food-grade certification entry in its final TDS. Review the documentation for the intended water use and complete construction detail.', 'trubuild-aqualock-flexi'],
      ['Crystalline concrete treatment', 'Crystaseal 1K is a crystalline treatment for concrete. Select its application method and follow its curing instructions as part of the water-retaining structure specification.', 'trubuild-crystaseal-1k'],
    ],
    steps: [
      ['Define the service conditions', 'Record whether the structure stores drinking water, other water or serves as a pool. Check the substrate, water pressure, existing lining, joints and pipe penetrations.'],
      ['Prepare and apply the system', 'Repair defects and complete joint and entry details before coating. Use the specified mixing ratio, coverage and coat sequence without unapproved dilution.'],
      ['Cure before filling', 'Allow the product-specific curing period, then follow the filling and testing procedure. For tiled pools, coordinate the waterproofing with an adhesive, grout and sealant suited to the service conditions.'],
    ],
    faqs: [
      ['Can TRU PU be used inside a water tank?', 'No. The final TRU PU TDS excludes permanent immersion, including tanks and pools. Its protected waterproofing applications should not be extended to a continuously water-filled structure.'],
      ['When can an Aqualock-coated tank be filled?', 'The final Aqualock TDS requires at least seven days before filling tanks or ponding tests. Aqualock Flexi also specifies at least seven days. Follow the full application, curing and filling instructions for the selected product.'],
      ['Is every waterproof coating suitable for drinking-water tanks?', 'No. Waterproofing performance alone does not establish suitability for contact with drinking water. Check the specific product documentation and relevant water-contact certification for the intended use; do not apply a claim from one product to the whole range.'],
      ['Do swimming pool tiles replace waterproofing?', 'No. The tile finish, adhesive and grout are parts of a pool system. The underlying waterproofing, construction joints and penetrations still need their specified treatment.'],
    ],
    related: ['tiling', 'basement', 'sealants'], documents: ['trubuild-aqualock', 'trubuild-aqualock-flexi', 'trubuild-crystaseal-1k'],
  },
  sealants: {
    title: 'Joint Sealants & Expansion Joint Sealing | TruBuild',
    description: 'Explore TruBuild joint sealing with Sealmaster Flexi. Understand movement joints, substrate preparation, sealant selection and technical data.',
    heading: 'Professional', accent: 'Sealants.',
    keywords: ['joint sealant', 'expansion joint sealant', 'MS polymer sealant', 'construction joint sealing', 'sealant vs crack filler'],
    question: 'When should you use an elastic joint sealant?',
    answer: 'Use an elastic joint sealant where a specified joint needs to accommodate movement while maintaining a seal. Select it for the substrates, expected movement, joint geometry and exposure. A non-structural plaster crack filler or rigid tile grout is not an automatic substitute for a movement-joint sealant.',
    intro: 'A gap between materials may open and close as the construction moves. Joint design and adhesion to its sides matter as much as the sealant chemistry. TruBuild Sealmaster Flexi is a single-component MS-polymer sealant documented for gap filling, control and expansion joints, and specified bonding applications.',
    selectionTitle: 'Define the joint before choosing the material.',
    choices: [
      ['Control and expansion joints', 'Review Sealmaster Flexi for the required substrates and movement. Its final TDS reports movement accommodation of ±50%; this is a product test value, not a substitute for calculating the joint dimensions.', 'trubuild-sealmaster-flexi'],
      ['Paintable elastic sealing', 'Sealmaster Flexi is described as paintable and weather resistant. Check substrate and finish compatibility, and follow the tooling and curing requirements for the application.', 'trubuild-sealmaster-flexi'],
      ['A static plaster crack instead', 'Crackfill Paste addresses suitable non-structural plastered masonry cracks. Its TDS excludes expansion joints, so distinguish a crack repair from a designed movement joint.', 'trubuild-crack-filler-cfp-425'],
    ],
    steps: [
      ['Record the joint', 'Identify both substrates, gap width and depth, expected movement and exposure. Use the project joint detail to establish the required geometry and material suitability.'],
      ['Prepare adhesion surfaces', 'For Sealmaster Flexi, the TDS calls for clean, dry, grease-free surfaces. Prepare the joint and any backing or bond-break arrangement specified by the joint design.'],
      ['Apply and tool', 'Apply Sealmaster Flexi with a sausage gun, tool before skin formation and remove masking tape before the sealant skins. Allow curing in accordance with the TDS before service.'],
    ],
    faqs: [
      ['What is the difference between sealant and crack filler?', 'A sealant is selected for a joint and its movement and exposure requirements. Crackfill Paste is intended for specified non-structural plaster cracks and excludes expansion joints. Select by the type of defect or joint, not simply by the gap being visible.'],
      ['What type of sealant is Sealmaster Flexi?', 'Sealmaster Flexi is a single-component MS-polymer elastomeric joint sealant. It cures with atmospheric moisture and is supplied in a 600 ml pack, according to its final TDS.'],
      ['Can Sealmaster Flexi be painted?', 'The final TDS describes Sealmaster Flexi as paintable. Check compatibility with the intended coating and allow the specified curing conditions; a painted finish must also suit the joint movement.'],
      ['Does elongation at break define the allowed joint movement?', 'No. Elongation at break and movement accommodation are different properties. The final Sealmaster Flexi TDS reports elongation above 500% and movement accommodation of ±50%. Use the relevant movement rating with the specified joint design.'],
    ],
    related: ['exterior', 'tiling', 'basement'], documents: ['trubuild-sealmaster-flexi', 'trubuild-crack-filler-cfp-425'],
  },
};
